export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_EMPLOYEE = 'SET_CURRENT_EMPLOYEE';

export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';
export const GET_ALL_EMPLOYEES_SUCSSES = 'GET_ALL_EMPLOYEES_SUCSSES';
export const GET_ALL_EMPLOYEES_FAILER = 'GET_ALL_EMPLOYEES_FAILER';

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
