export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_EMPLOYEE = 'SET_CURRENT_EMPLOYEE';

export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';
export const GET_ALL_EMPLOYEES_SUCSSES = 'GET_ALL_EMPLOYEES_SUCSSES';
export const GET_ALL_EMPLOYEES_FAILER = 'GET_ALL_EMPLOYEES_FAILER';

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const GET_ALL_CAGES_SUCSSES = 'GET_ALL_CAGES_SUCSSES';
export const GET_ALL_CAGES_FAILER = 'GET_ALL_CAGES_FAILER';

export const DELETE_CAGE = 'DELETE_CAGE';

export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
export const GET_ALL_CLIENTS_SUCSSES = 'GET_ALL_CLIENTS_SUCSSES';
export const GET_ALL_CLIENTS_FAILER = 'GET_ALL_CLIENTS_FAILER';

export const DELETE_CLIENT = 'DELETE_CLIENT';

export const GET_ALL_PRODUCTS_SUCSSES = 'GET_ALL_PRODUCTS_SUCSSES';
export const GET_ALL_PRODUCTS_FAILER = 'GET_ALL_PRODUCTS_FAILER';

export const ADD_PRODUCT_SUCSSES = 'ADD_PRODUCT_SUCSSES';
export const ADD_PRODUCT_FAILER = 'ADD_PRODUCT_FAILER';

export const DELETE_PRODUCTS_SUCSSES = 'DELETE_PRODUCTS_SUCSSES';
export const DELETE_PRODUCTS_FAILER = 'DELETE_PRODUCTS_FAILER ';

export const GET_ALL_SCHEDULES_SUCSSES = 'GET_ALL_SCHEDULES_SUCSSES';
export const GET_ALL_SCHEDULES_FAILER = 'GET_ALL_SCHEDULES_FAILER';

export const GET_ALL_EMPLOYEE_SCHEDULES_SUCSSES =
  'GET_ALL_EMPLOYEE_SCHEDULES_SUCSSES';
export const GET_ALL_EMPLOYEE_SCHEDULES_FAILER =
  'GET_ALL_EMPLOYEE_SCHEDULES_FAILER';

export const ADD_SCHEDULE_SUCSSES = 'ADD_SCHEDULE_SUCSSES';
export const ADD_SCHEDULE_FAILER = 'ADD_SCHEDULE_FAILER';

export const UPDATE_SCHEDULE_SUCSSES = 'UPDATE_SCHEDULE_SUCSSES';
export const UPDATE_SCHEDULE_FAILER = 'UPDATE_SCHEDULE_FAILER';

export const DELETE_SCHEDULE_SUCSSES = 'DELETE_SCHEDULE_SUCSSES';
export const DELETE_SCHEDULE_FAILER = 'DELETE_SCHEDULE_FAILER';

export const GET_ALL_ORDERS_SUCSSES = 'GET_ALL_ORDERS_SUCSSES';
export const GET_ALL_ORDERS_FAILER = 'GET_ALL_ORDERS_FAILER';

export const ADD_ORDERS_SUCSSES = 'ADD_ORDERS_SUCSSES';
export const ADD_ORDERS_FAILER = 'ADD_ORDERS_FAILER';

export const GET_ALL_INFO_FOR_ORDERS_SUCSSES =
  'GET_ALL_INFO_FOR_ORDERS_SUCSSES';
export const GET_ALL_INFO_FOR_ORDERS_FAILER = 'GET_ALL_INFO_FOR_ORDERS_FAILER';

export const DELETE_ORDER_SUCSSES = 'DELETE_ORDER_SUCSSES';
export const DELETE_ORDER_FAILER = 'DELETE_ORDER_FAILER';

export const UPDATE_CAGE_SUCSSES = 'UPDATE_CAGE_SUCSSES';
export const UPDATE_CAGE_FAILER = 'UPDATE_CAGE_FAILER';

export const UPDATE_PRODUCT_SUCSSES = 'UPDATE_PRODUCT_SUCSSES';
export const UPDATE_PRODUCT_FAILER = 'UPDATE_PRODUCT_FAILER';

export const UPDATE_EMPLOYEE_SUCSSES = 'UPDATE_EMPLOYEE_SUCSSES';
export const UPDATE_EMPLOYEE_FAILER = 'UPDATE_EMPLOYEE_FAILER';

export const UPDATE_CLIENT_SUCSSES = 'UPDATE_CLIENT_SUCSSES';
export const UPDATE_CLIENT_FAILER = 'UPDATE_CLIENT_FAILER';
